parameters:
#    nana_blog.example.class: Nana\BlogBundle\Example

services:
#    nana_blog.example:
#        class: %nana_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     twig.extension.txt: 
         class: Twig_Extensions_Extension_Text 
         tags: 
             - { name: twig.extension }
