<?php

namespace Nana\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembersRepository extends EntityRepository
{
}