parameters:
#    nana_manage.example.class: Nana\ManageBundle\Example

services:
#    nana_manage.example:
#        class: %nana_manage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
